"""indexes_on_hot_columns

Revision ID: 11d30a33e2fc
Revises: bd9429f9dfc7
Create Date: 2026-04-15 13:43:57.785991

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11d30a33e2fc'
down_revision: Union[str, Sequence[str], None] = 'bd9429f9dfc7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deal_chats', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_deal_chats_deal_id'), ['deal_id'], unique=False)

    with op.batch_alter_table('deal_documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_deal_documents_deal_id'), ['deal_id'], unique=False)

    with op.batch_alter_table('deals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_deals_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_deals_developer_id'), ['developer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_deals_status'), ['status'], unique=False)

    with op.batch_alter_table('developers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_developers_deleted_at'), ['deleted_at'], unique=False)

    with op.batch_alter_table('distributions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_distributions_investment_id'), ['investment_id'], unique=False)

    with op.batch_alter_table('investments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_investments_deal_id'), ['deal_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_investments_deleted_at'), ['deleted_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('investments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_investments_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_investments_deal_id'))

    with op.batch_alter_table('distributions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_distributions_investment_id'))

    with op.batch_alter_table('developers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_developers_deleted_at'))

    with op.batch_alter_table('deals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_deals_status'))
        batch_op.drop_index(batch_op.f('ix_deals_developer_id'))
        batch_op.drop_index(batch_op.f('ix_deals_deleted_at'))

    with op.batch_alter_table('deal_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_deal_documents_deal_id'))

    with op.batch_alter_table('deal_chats', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_deal_chats_deal_id'))

    # ### end Alembic commands ###
