"""initial_schema

Revision ID: 9d8412c8b16d
Revises: 
Create Date: 2026-04-14 22:49:55.859914

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d8412c8b16d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('developers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('contact_name', sa.String(length=255), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('track_record', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('developers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_developers_id'), ['id'], unique=False)

    op.create_table('deals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('developer_id', sa.Integer(), nullable=True),
    sa.Column('project_name', sa.String(length=500), nullable=False),
    sa.Column('location', sa.String(length=500), nullable=True),
    sa.Column('city', sa.String(length=255), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('property_type', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('metrics', sa.JSON(), nullable=True),
    sa.Column('scores', sa.JSON(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('location_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['developer_id'], ['developers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('deals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_deals_id'), ['id'], unique=False)

    op.create_table('deal_chats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deal_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('deal_chats', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_deal_chats_id'), ['id'], unique=False)

    op.create_table('deal_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deal_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=500), nullable=False),
    sa.Column('file_path', sa.String(length=1000), nullable=False),
    sa.Column('doc_type', sa.String(length=50), nullable=True),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('upload_date', sa.DateTime(), nullable=True),
    sa.Column('extraction_quality', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('deal_documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_deal_documents_id'), ['id'], unique=False)

    op.create_table('investments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deal_id', sa.Integer(), nullable=True),
    sa.Column('project_name', sa.String(length=500), nullable=True),
    sa.Column('sponsor_name', sa.String(length=255), nullable=True),
    sa.Column('investment_date', sa.Date(), nullable=True),
    sa.Column('amount_invested', sa.Float(), nullable=True),
    sa.Column('shares', sa.Float(), nullable=True),
    sa.Column('investment_class', sa.String(length=100), nullable=True),
    sa.Column('preferred_return', sa.Float(), nullable=True),
    sa.Column('projected_irr', sa.Float(), nullable=True),
    sa.Column('projected_equity_multiple', sa.Float(), nullable=True),
    sa.Column('hold_period_years', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('exit_date', sa.Date(), nullable=True),
    sa.Column('exit_amount', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('investments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_investments_id'), ['id'], unique=False)

    op.create_table('distributions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('investment_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('dist_type', sa.String(length=50), nullable=True),
    sa.Column('period', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['investment_id'], ['investments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('distributions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_distributions_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('distributions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_distributions_id'))

    op.drop_table('distributions')
    with op.batch_alter_table('investments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_investments_id'))

    op.drop_table('investments')
    with op.batch_alter_table('deal_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_deal_documents_id'))

    op.drop_table('deal_documents')
    with op.batch_alter_table('deal_chats', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_deal_chats_id'))

    op.drop_table('deal_chats')
    with op.batch_alter_table('deals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_deals_id'))

    op.drop_table('deals')
    with op.batch_alter_table('developers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_developers_id'))

    op.drop_table('developers')
    # ### end Alembic commands ###
