"""add_deleted_at_for_soft_delete

Revision ID: ba331b305ee8
Revises: 9d8412c8b16d
Create Date: 2026-04-14 22:59:21.500901

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba331b305ee8'
down_revision: Union[str, Sequence[str], None] = '9d8412c8b16d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('developers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('investments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('investments', schema=None) as batch_op:
        batch_op.drop_column('deleted_at')

    with op.batch_alter_table('developers', schema=None) as batch_op:
        batch_op.drop_column('deleted_at')

    with op.batch_alter_table('deals', schema=None) as batch_op:
        batch_op.drop_column('deleted_at')

    # ### end Alembic commands ###
